### PR TITLE
Language Argument and fixed tests

### PR DESCRIPTION
**Pull request by MaxBittker**
This pull request implements a new argument 'lang' which allows you to query all 288 Wikipedia languages!  Defaults to English which means it's also backwards compatible.
I also fixed the tests which were broken due to some pages changing their wording, and the wddx api being deprecated. I don't know why travis is currently reporting build passing, because about half of the test failed on my machine when I first cloned. 
I apologize for the formatting changes, I use a popular javascript formatter and forgot I had it on. 

Thanks for putting out this package! I've been using it to train my neural network.

### CODE REVIEW

**Comment by kenshiro-o** [comment]
Hey @MaxBittker . It seems the Travis build failed because it could not pull some of the dependencies. Could you please make sure this is sorted before I can merge the PR :wink:

**Comment by MaxBittker** [comment]
I'm pretty sure the problem is related to travis's npm/node version. I updated .travis.yml and may have fixed it, but it's yet to rebuild for some reason. If you see this and travis still hasn't built c0407d5, would you mind triggering a build manually? It also might just be missing something, new to using Travis. Thanks!

**Comment by MaxBittker** [comment]
:+1: travis is happy! rebuild wasn't triggering because there was a merge conflict. let me know if you have any other concerns

**Comment by MaxBittker** [comment]
@kenshiro-o sorry to be annoying, just pinging this back to the top of your notifications before we both forget about it :ice_cream:

**Comment by kenshiro-o** [comment]
@MaxBittker Done! Sorry for the delay!

**Pull request merged**
